### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by snoop123** [zephrax/serverless-consul-variables#7]
Hi!

I'm using serverless latest version 3.22.00 with the following consul configuration:

```
plugins:
  -serverless-consul-variables
custom:
   serverless-consul-variables:
     consul_settings:
       host: consul.service.op-$AWS_REGION.consul
       port: 8500
   service:
    enable_registration: true
    enpdoint_filters: '^api(.*)'
    consul_endpoint_key_path: 'dev_test/serverless/endpoints'
```

But when running 'serverless print' I get the following error:

```
>>serverless print
Running "serverless" from node_modules
Environment: darwin, node 18.9.0, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'bind')
    at new ServerlessConsulVariables (/workspace/serverless/project/node_modules/serverless-consul-variables/dist/index.js:89:27)
    at PluginManager.addPlugin (/workspace/serverless/project/node_modules/serverless/lib/classes/plugin-manager.js:91:28)
    at /workspace/serverless/project/node_modules/serverless/lib/classes/plugin-manager.js:137:69
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/workspace/serverless/project/node_modules/serverless/lib/classes/plugin-manager.js:137:44)
    at async Serverless.init (/workspace/serverless/project/node_modules/serverless/lib/serverless.js:141:5)
    at async /workspace/serverless/project/node_modules/serverless/scripts/serverless.js:591:7

```

I would appreciate your help
